# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import torch
print(f"Is GPU available? {torch.cuda.is_available()}")
print(f"GPU Name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")

# 1. Install MONAI (Medical Open Network for AI)
!pip install -q monai nibabel

import torch
import numpy as np
from monai.transforms import (
    Compose, EnsureChannelFirstd, ScaleIntensityd,
    RandGaussianNoised, ToTensord
)

# 2. Define the 'Distortion' Pipeline
# We take a clear image and make it noisy so the AI can learn to 'fix' it.
mri_pipeline = Compose([
    # Scales the MRI pixel values to [0, 1] for better math stability
    ScaleIntensityd(keys=["image"]),
    # Adds random noise (Simulating a low-quality scanner)
    RandGaussianNoised(keys=["image"], prob=1.0, std=0.2),
    ToTensord(keys=["image"])
])

print("Medical AI environment ready!")

from monai.networks.nets import UNet

# Define the 'Brain' of our project
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = UNet(
    spatial_dims=2,          # We are working with 2D slices of the MRI
    in_channels=1,           # Input: 1 noisy image
    out_channels=1,          # Output: 1 clean image
    channels=(16, 32, 64, 128, 256), # The 'depth' of the brain (more channels = more features)
    strides=(2, 2, 2, 2),    # How it 'shrinks' the image to understand it
).to(device)

print(f"U-Net Model initialized and moved to {device}")

import torch.optim as optim
import torch.nn as nn

# The Judge: Measures how far we are from the 'perfect' image
loss_function = nn.MSELoss()

# The Teacher: Updates the AI's internal logic
optimizer = optim.Adam(model.parameters(), lr=1e-3)

print("Loss function and Optimizer are set. Ready to train.")

import os
import urllib.request

# URL for a sample brain MRI (T1-weighted)
mri_url = "https://github.com/neurolabusc/niivue-images/raw/main/chris_t1.nii.gz"
mri_filename = "brain_sample.nii.gz"

if not os.path.exists(mri_filename):
    print("Downloading real brain MRI sample...")
    urllib.request.urlretrieve(mri_url, mri_filename)
    print("Download complete.")
else:
    print("MRI file already exists.")

import torch.nn.functional as F

# 1. Load and slice
img_data = nib.load(mri_filename).get_fdata()
slice_idx = img_data.shape[2] // 2
clean_slice = img_data[:, :, slice_idx]

# 2. THE SECRET SAUCE: Min-Max Normalization
# This squashes the pixels from [0, 2000] down to [0, 1]
clean_slice = (clean_slice - clean_slice.min()) / (clean_slice.max() - clean_slice.min())

# 3. Crop to 128x128
h, w = clean_slice.shape
start_h, start_w = h//2 - 64, w//2 - 64
clean_slice = clean_slice[start_h:start_h+128, start_w:start_w+128]

# 4. Add subtle noise (0.1 is standard for medical denoising)
noise_factor = 0.1
noisy_slice = clean_slice + noise_factor * np.random.normal(size=clean_slice.shape)

# 5. Prepare for GPU
input_data = torch.from_numpy(noisy_slice).float().unsqueeze(0).unsqueeze(0).to(device)
target_data = torch.from_numpy(clean_slice).float().unsqueeze(0).unsqueeze(0).to(device)

print("Data Normalized! Ready for smooth learning.")

# Calculate the absolute difference (Residual)
residual = np.abs(clean_slice - noisy_slice)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.title("Input to AI (Looks Clean to Us)")
plt.imshow(noisy_slice.T, cmap='gray', origin='lower')
plt.axis('off')

plt.subplot(1, 2, 2)
# We use the 'hot' colormap to highlight the tiny pixel differences
plt.title("What the AI 'Sees' (Residual Noise)")
plt.imshow(residual.T, cmap='hot', origin='lower')
plt.colorbar(label="Error Intensity")
plt.axis('off')

plt.show()

import torch.optim as optim

# 1. Reset the model so we start from a clean slate
model.apply(lambda m: m.reset_parameters() if hasattr(m, 'reset_parameters') else None)

# 2. Optimized Teacher (Lower learning rate for stability)
optimizer = optim.Adam(model.parameters(), lr=5e-4)

print("Starting deep training (500 Epochs)...")

for epoch in range(501):
    model.train()
    optimizer.zero_grad()

    output = model(input_data)
    loss = loss_function(output, target_data)

    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch} | Loss: {loss.item():.6f}")

print("Deep Learning Complete!")

model.eval()
with torch.no_grad():
    # Pass the noisy image through the 'Brain'
    denoised_output = model(input_data).cpu().squeeze().numpy()

# Plotting the Triple-Check (The standard for a CV project)
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.title("Original (Clean Target)")
plt.imshow(clean_slice.T, cmap='gray', origin='lower')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title("Distorted (AI Input)")
plt.imshow(noisy_slice.T, cmap='gray', origin='lower')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title("AI Result (Denoised)")
plt.imshow(denoised_output.T, cmap='gray', origin='lower')
plt.axis('off')

plt.show()

from fastapi import FastAPI, UploadFile, File
import io
from PIL import Image
import uvicorn
import nest_asyncio
import asyncio

# 1. Initialize the FastAPI app
app = FastAPI(title="MRI Denoising API")

@app.post("/denoise")
async def denoise_mri(file: UploadFile = File(...)):
    # Read the uploaded file
    contents = await file.read()
    image = Image.open(io.BytesIO(contents)).convert("L")
    
    # Preprocess (Resizing to match your 128x128 training)
    image = image.resize((128, 128))
    img_array = np.array(image) / 255.0
    input_tensor = torch.from_numpy(img_array).float().view(1, 1, 128, 128).to(device)
    
    # AI Inference
    model.eval()
    with torch.no_grad():
        output = model(input_tensor).cpu().squeeze().numpy()
    
    return {
        "status": "Success", 
        "message": "MRI processed through U-Net",
        "output_shape": str(output.shape)
    }

# 2. Allow nested event loops for Colab
nest_asyncio.apply()

# 3. Configure and start the server
config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
server = uvicorn.Server(config)

print("Server is starting on http://localhost:8000")
await server.serve()
